# Generated by Django 3.2.12 on 2023-06-06 12:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_content', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='完了')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('response_content', tinymce.models.HTMLField(blank=True, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'st課題管理',
            },
        ),
    ]
