# Generated by Django 3.2.12 on 2022-10-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商用サイズ')),
            ],
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商用ボティタイプ')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='メーカー')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='乗用サイズ')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='乗用ボティタイプ')),
            ],
        ),
        migrations.CreateModel(
            name='CarForPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='車名')),
                ('base_digit', models.CharField(blank=True, max_length=200, null=True, verbose_name='基本3桁')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='コード')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('cargo_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myprofit.cargosize', verbose_name='商用サイズ')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myprofit.cargotype', verbose_name='商用ボティタイプ')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprofit.maker', verbose_name='メーカー')),
                ('passenger_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myprofit.passengersize', verbose_name='乗用サイズ')),
                ('passenger_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myprofit.passengertype', verbose_name='乗用ボティタイプ')),
            ],
        ),
    ]
