version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django2prod
    volumes:
      # - ./:/code:cached
      - ./:/code:consistent
      # - static_volume:/code/static
      - ./static:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - TZ=Asia/Tokyo

  db:
    image: postgres:13.5
    container_name: db2prod
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - TZ=Asia/Tokyo

  nginx-proxy:
    container_name: nginx-proxy2prod
    build:
      context: ./nginx/
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      # - static_volume:/code/static
      - ./static:/code/static
      - media_volume:/code/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html #OneSignalSDKWorker.jsコピーが上書きされないようコメントアウトした
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - django
    environment:
      - TZ=Asia/Tokyo


  nginx-proxy-letsencrypt:
    # image: jrcs/letsencrypt-nginx-proxy-companion
    image: nginxproxy/acme-companion
    container_name: letsencrypt2prod
    env_file:
      - .env.prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    environment:
      - TZ=Asia/Tokyo

volumes:
  db-data:
  # static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: