# Generated by Django 3.2.12 on 2022-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_auto_20220410_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
