# Generated by Django 3.2.12 on 2022-04-18 09:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0004_auto_20220415_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(blank=True, null=True)),
                ('answer1', tinymce.models.HTMLField(blank=True, null=True)),
                ('answer2', tinymce.models.HTMLField(blank=True, null=True)),
                ('reference', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
