# Generated by Django 3.2.12 on 2022-05-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0005_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming', models.CharField(max_length=20, verbose_name='相手')),
                ('name', models.TextField(max_length=100, verbose_name='窓口')),
                ('title', models.TextField(max_length=100, verbose_name='業務')),
                ('job', models.TextField(max_length=1000, verbose_name='詳細')),
                ('tel', models.TextField(max_length=100, verbose_name='TEL')),
                ('hours', models.TextField(max_length=100, verbose_name='時間')),
                ('searchwords', models.CharField(blank=True, max_length=200, null=True, verbose_name='検索ワード')),
                ('attachments', models.ManyToManyField(blank=True, to='myinfo.Attachments')),
            ],
            options={
                'verbose_name_plural': '問い合わせ先',
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code5', models.CharField(max_length=10, verbose_name='コード5桁')),
                ('code4', models.CharField(max_length=10, verbose_name='コード4桁')),
                ('name', models.CharField(max_length=50, verbose_name='販社略')),
                ('full_name', models.CharField(max_length=50, verbose_name='販社フル')),
                ('domain', models.CharField(max_length=100, verbose_name='ドメイン')),
                ('customer_desk', models.CharField(max_length=50, verbose_name='お客様相談室')),
                ('emergency', models.CharField(max_length=50, verbose_name='緊急サポートダイヤル')),
                ('bc', models.CharField(max_length=50, verbose_name='BC本部')),
                ('nfs', models.CharField(max_length=50, verbose_name='NFSメンテ')),
                ('in_house', models.CharField(max_length=50, verbose_name='自社メンテ')),
                ('base', models.CharField(max_length=50, verbose_name='事務所')),
                ('base_tel', models.CharField(max_length=50, verbose_name='事務所TEL')),
            ],
            options={
                'verbose_name_plural': '販社',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='店名')),
                ('shopcode', models.CharField(max_length=10, null=True, verbose_name='店舗コード')),
                ('tel', models.CharField(max_length=50, null=True, verbose_name='TEL')),
                ('fax', models.CharField(max_length=50, null=True, verbose_name='FAX')),
                ('homepage', models.CharField(max_length=200, null=True, verbose_name='H.P.')),
                ('memo', models.CharField(max_length=100, null=True, verbose_name='メモ')),
                ('kana', models.CharField(max_length=50, null=True, verbose_name='フリガナ')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myinfo.dealers')),
            ],
            options={
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.RemoveField(
            model_name='information',
            name='category',
        ),
        migrations.AddField(
            model_name='faqs',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='myinfo.Attachments'),
        ),
        migrations.AddField(
            model_name='information',
            name='freeword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='InfoCategory',
        ),
        migrations.AddField(
            model_name='contacts',
            name='dealers',
            field=models.ManyToManyField(blank=True, to='myinfo.Dealers'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='myinfo.Contacts'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='dealers',
            field=models.ManyToManyField(blank=True, to='myinfo.Dealers'),
        ),
    ]
