# Generated by Django 3.2.12 on 2022-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0005_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
