# Generated by Django 3.2.12 on 2022-05-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_faqs_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='myinfo.Attachments'),
        ),
    ]
