# Generated by Django 3.2.12 on 2022-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220511_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='category',
        ),
        migrations.AddField(
            model_name='information',
            name='freeword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='InfoCategory',
        ),
    ]
