# Generated by Django 3.2.12 on 2022-05-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220514_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='attachments',
        ),
    ]
