# Generated by Django 3.2.12 on 2022-05-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220507_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='dealers',
        ),
    ]
