# Generated by Django 3.2.12 on 2022-05-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0007_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='non_html',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='non_html',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='non_html',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
