# Generated by Django 3.2.12 on 2022-05-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0005_rename_code5_shops_dealer'),
        ('myinfo', '0007_faqs_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='dealers',
            field=models.ManyToManyField(blank=True, to='mycontact.Dealers'),
        ),
    ]
