# Generated by Django 3.2.12 on 2022-05-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0007_remove_contacts_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttachRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myinfo.attachments')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myinfo.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='attachments',
            field=models.ManyToManyField(blank=True, through='myinfo.ContactAttachRel', to='myinfo.Attachments'),
        ),
    ]
