# Generated by Django 3.2.12 on 2022-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0008_nonhtml_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='searchwords',
            new_name='for_search',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='freeword',
            new_name='for_search',
        ),
        migrations.AddField(
            model_name='note',
            name='for_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
