# Generated by Django 3.2.12 on 2022-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0011_onesignaluser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', '発送なし'), ('2', 'VCC休み'), ('3', '非表示にする日')], max_length=100, verbose_name='分類')),
                ('non_date', models.DateField(verbose_name='対象日')),
            ],
            options={
                'verbose_name_plural': '休業日',
            },
        ),
    ]
