# Generated by Django 3.2.12 on 2022-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0012_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='non_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='non_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='non_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
