# Generated by Django 3.2.12 on 2022-08-31 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0013_nonhtml_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, max_length=50, null=True, verbose_name='店舗')),
                ('shopcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='店舗コード')),
                ('cacode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CAコード')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CA名')),
                ('kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAカナ')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myinfo.dealers')),
            ],
            options={
                'verbose_name_plural': 'CA',
            },
        ),
    ]
