# Generated by Django 3.2.12 on 2022-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0014_cas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hiru_0', models.TextField(blank=True, null=True)),
                ('hiru_1', models.TextField(blank=True, null=True)),
                ('hiru_2', models.TextField(blank=True, null=True)),
                ('hiru_3', models.TextField(blank=True, null=True)),
                ('hiru_4', models.TextField(blank=True, null=True)),
                ('hiru_5', models.TextField(blank=True, null=True)),
                ('hiru_6', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'FAX当番',
            },
        ),
    ]
