# Generated by Django 3.2.12 on 2022-10-18 05:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0015_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaxFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '書式（FAXルール）',
            },
        ),
        migrations.CreateModel(
            name='FaxExplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('fax_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myinfo.faxformats')),
            ],
            options={
                'verbose_name_plural': 'FAXルール説明',
            },
        ),
    ]
