# Generated by Django 3.2.12 on 2023-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0017_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshifts',
            name='sort_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
