# Generated by Django 3.0.4 on 2022-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming', models.CharField(max_length=20, verbose_name='相手')),
                ('name', models.CharField(max_length=50, verbose_name='窓口')),
                ('title', models.CharField(max_length=50, verbose_name='概要')),
                ('job', models.TextField(max_length=1000, verbose_name='対応内容詳細')),
                ('tel', models.CharField(max_length=50, verbose_name='TEL')),
                ('hours', models.CharField(max_length=50, verbose_name='営業時間')),
                ('searchwords', models.CharField(max_length=200, null=True, verbose_name='検索ワード')),
            ],
            options={
                'verbose_name_plural': '問い合わせ先',
            },
        ),
    ]
