# Generated by Django 3.0.4 on 2022-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='hours',
            field=models.TextField(max_length=100, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='job',
            field=models.TextField(max_length=1000, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.TextField(max_length=100, verbose_name='窓口'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='searchwords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='検索ワード'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=models.TextField(max_length=100, verbose_name='TEL'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.TextField(max_length=100, verbose_name='業務'),
        ),
    ]
