# Generated by Django 3.2.12 on 2022-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0002_auto_20220405_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code5', models.CharField(max_length=10, verbose_name='コード5桁')),
                ('code4', models.CharField(max_length=10, verbose_name='コード4桁')),
                ('name', models.CharField(max_length=50, verbose_name='販社略')),
                ('full_name', models.CharField(max_length=50, verbose_name='販社フル')),
                ('domain', models.CharField(max_length=100, verbose_name='ドメイン')),
                ('customer_desk', models.CharField(max_length=50, verbose_name='お客様相談室')),
                ('emergency', models.CharField(max_length=50, verbose_name='緊急サポートダイヤル')),
                ('bc', models.CharField(max_length=50, verbose_name='BC本部')),
                ('nfs', models.CharField(max_length=50, verbose_name='NFSメンテ')),
                ('in_house', models.CharField(max_length=50, verbose_name='自社メンテ')),
                ('base', models.CharField(max_length=50, verbose_name='事務所')),
                ('base_tel', models.CharField(max_length=50, verbose_name='事務所TEL')),
            ],
            options={
                'verbose_name_plural': '販社',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
