# Generated by Django 3.2.12 on 2022-05-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0007_auto_20220512_1119'),
        ('mycontact', '0006_auto_20220507_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='dealer',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Dealers',
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
