FROM jwilder/nginx-proxy
COPY vhost.d/default /etc/nginx/vhost.d/default
COPY custom.conf /etc/nginx/conf.d/custom.conf
COPY OneSignalSDKWorker.js /usr/share/nginx/html/OneSignalSDKWorker.js
#20220814試行
COPY html/custom_pages/ /etc/nginx/html/custom_pages/
#RUN mkdir -p /etc/nginx/html/custom_pages/