# Generated by Django 3.2.12 on 2022-05-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0003_auto_20220502_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='店名')),
                ('shopcode', models.CharField(max_length=10, null=True, verbose_name='店舗コード')),
                ('tel', models.CharField(max_length=50, null=True, verbose_name='TEL')),
                ('fax', models.CharField(max_length=50, null=True, verbose_name='FAX')),
                ('homepage', models.CharField(max_length=200, null=True, verbose_name='H.P.')),
                ('memo', models.CharField(max_length=100, null=True, verbose_name='メモ')),
                ('kana', models.CharField(max_length=50, null=True, verbose_name='フリガナ')),
                ('code5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mycontact.dealers')),
            ],
            options={
                'verbose_name_plural': '店舗',
            },
        ),
    ]
