# Generated by Django 3.2.12 on 2022-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220507_1201'),
        ('mycontact', '0005_rename_code5_shops_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='myinfo.Attachments'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='dealers',
            field=models.ManyToManyField(blank=True, to='mycontact.Dealers'),
        ),
    ]
