# Generated by Django 3.2.12 on 2022-05-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220507_1201'),
        ('mycontact', '0006_auto_20220507_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttachRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myinfo.attachments')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycontact.contacts')),
            ],
            options={
                'verbose_name_plural': '問い合わせ添付の中間テーブル',
            },
        ),
    ]
