# Generated by Django 3.2.12 on 2022-05-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20220507_1201'),
        ('mycontact', '0007_contactattachrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactattachrel',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactattach_rel', to='myinfo.attachments'),
        ),
    ]
